### ISSUE TITLE
默认地址会自动清除

### ISSUE THREAD

**Issue by owenstudy** [bran4he/FruitSMSDemo#15]
在输入一个新的地址并设置为默认地址保存成功后这时这个默认地址是正确的。
再创建一个新的订单，这个默认地址会被取出来，然后保存时还是按默认地址来保存就会出现保存后，这个地址的默认标志被清除。 
我前台跟踪了发现提交的URL是对的，都是加了那个参数为默认地址的1，只是保存成功后后台就把这个默认地址给清除了，估计后面有取反逻辑的处理。

**Comment by bran4he** [comment]
【下订单且设为默认地址请求】
确认逻辑错误，已经修复：
1. 先查找是否有一样的地址，
1.1 有一样的，默认地址直接return，非默认更新为默认
1.2 没有一样的，将其他地址设为非默认，将此地址设为默认
