### ISSUE TITLE
水果删除异常

### ISSUE THREAD

**Issue by owenstudy** [bran4he/FruitSMSDemo#16]
在做水果删除操作时有异常，看后台报了一堆错误，你看看是怎么回事？
正常的逻辑只要是没有下过订单的水果应该是可以删除的。

**Comment by bran4he** [comment]
测试结果：
水果test没有下单，可以被删除。
水果黄瓜有订单，不能被删除。

测试没有异常，需要提供没有下单却不能删除的水果例子。

**Comment by bran4he** [comment]
closed as cannot be reproduced
