### ISSUE TITLE
订单的派送日期不对

### ISSUE THREAD

**Issue by owenstudy** [bran4he/FruitSMSDemo#19]
1. 订单在后台点击派送中后，在前台查询的订单派送日期为1970-1-1，看起来是放的一个默认值，这个值应该是放成当时点击派送中时的系统日期
2. 订单的默认备注如果不增加的话会自动增加一个default_remark，这个去掉吧，如果没有注释就放置为空。

**Comment by bran4he** [comment]
closed as resolved
