### ISSUE TITLE
订单保存报错

### ISSUE THREAD

**Issue by owenstudy** [bran4he/FruitSMSDemo#7]
更新的版本有点问题，你抽空看一下ＬＯＧ，我保存订单的时候报错了，看ＬＯＧ是有一个statusId=undefined,按道理保单订单的应该不会有这个状态的输入
Apr 28 01:07:31 tryfruit[26691]: 2017-04-28 01:07:31 INFO  IOrderController:60 - queryOrder, wechatId:oJePmvq9iaD3WMcZrpucFwZKn4OU and status:2
Apr 28 01:07:31 tryfruit[26691]: 2017-04-28 01:07:31 INFO  OrderDao:57 - iQueryUserOrder sql:
Apr 28 01:07:31 tryfruit[26691]: select oo.*, os.name as statusValue , aa.wechatOpenid as wechatOpenid from T_ORDER oo join T_ASSIGN aa on oo.assignId = aa.id join T_ORDER_STATUS os on oo.statusId = os.id WHERE wechatOpenid='oJePmvq9iaD3WMcZrpucFwZKn4OU' AND oo.statusId = 2 order by updateDate 
Apr 28 01:07:31 tryfruit[26691]: Apr 28, 2017 1:07:31 AM org.apache.catalina.core.StandardWrapperValve invoke
Apr 28 01:07:31 tryfruit[26691]: SEVERE: Servlet.service() for servlet [springMVC] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [select oo.*, os.name as statusValue , aa.wechatOpenid as wechatOpenid from T_ORDER oo join T_ASSIGN aa on oo.assignId = aa.id join T_ORDER_STATUS os on oo.statusId = os.id WHERE wechatOpenid='oJePmvq9iaD3WMcZrpucFwZKn4OU' AND oo.statusId = undefined order by updateDate ]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'undefined' in 'where clause'] with root cause
Apr 28 01:07:31 tryfruit[26691]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'undefined' in 'where clause'
Apr 28 01:07:31 tryfruit[26691]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Apr 28 01:07:31 tryfruit[26691]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Apr 28 01:07:31 tryfruit[26691]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Apr 28 01:07:31 tryfruit[26691]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Apr 28 01:07:31 tryfruit[26691]: 	at com.

**Comment by bran4he** [comment]
调用报错处是查询订单，不是生成订单：`IOrderController:60 - queryOrder, wechatId:oJePmvq9iaD3WMcZrpucFwZKn4OU and status:2`

调用接口`{{server}}/rest/order/query/oJePmvq9iaD3WMcZrpucFwZKn4OU/2`,返回正确：
```
{
  "code": "SUCCESS",
  "value": "0",
  "msg": "[{\"id\":\"25\",\"statusId\":\"2\",\"statusValue\":\"派送中\",\"assignId\":null,\"wechatOpenid\":\"oJePmvq9iaD3WMcZrpucFwZKn4OU\",\"orderDetail\":[{\"id\":\"33\",\"orderUnit\":2,\"fruitId\":\"3\",\"fruitName\":\"火龙果\"}],\"planDeliveryDate\":\"2017-04-28\",\"address\":\"rrrrtt\",\"contactName\":\"eeee\",\"contactPhone\":\"1323333666\",\"deliveryDate\":\"2017-05-05\",\"deliveryBy\":\"DeliveryBy\",\"deliveryRemark\":\"DeliveryRemark\",\"finishDate\":\"2017-05-05\",\"finishBy\":\"FinishBy\",\"finishRemark\":\"FinishRemark\",\"remark\":\"default_remark\",\"extendData\":null,\"insertDate\":\"2017-04-28\",\"updateDate\":\"2017-04-28\",\"insertBy\":\"unknown\",\"updateBy\":\"unknown\"}]"
}
```

错误暂时不能复现。

**Comment by bran4he** [comment]
closed as has been solved.
