### ISSUE TITLE
增加每个帐户最大的在途订单数量

### ISSUE THREAD

**Issue by owenstudy** [bran4he/FruitSMSDemo#8]
需要增加一个公共参数，用来设置一个帐户每个月允许的最大的订单数量，如每个用户每月最多只能下2个订单，并提供一个接口来访问这个参数
需要提供一个接口，用来统计当前用户已经下的订单数量（待派送的订单数量），以便用来判断系统存在的订单数量和公共参数中的最大订单量进行对比

**Comment by bran4he** [comment]
`需要提供一个接口，用来统计当前用户已经下的订单数量（待派送的订单数量）`

**Comment by bran4he** [comment]
**sample**
Request:
GET fruit/rest/order/waitForNums/QWERTYUIOP

Response:
```
{
  "code": "SUCCESS",
  "value": "0",
  "msg": "{\"count\":5}"
}
```

**Comment by bran4he** [comment]
查询在途订单的逻辑是，查询当月（insert time=当月），用户（openid），且在途的订单（订单状态=2 delivering）
